# config.yml

backend:
  name: github
  repo: cubetreemarketplace/cubetree-marketplace
  branch: cms

  media_folder: 'assets/uploads'

collections:
  - name: 'team'
    label: 'Team'
    folder: 'collections/_team/'
    fields:
      - { name: name }