# config.yml

backend:
  name: github
  repo: cubetreemarketplace/cubetree-marketplace
  branch: cms

logo_url: './../assets/img/cubetreeLogo_dark.svg'

media_folder: 'assets/uploads'

collections:
  - name: 'websiteInfo'
    label: 'Website Information'
    files:
      - label: 'Website Information'
        name: 'site'
        file: '_config.yml'
        fields:
          - label: 'Title'
            name: 'title'
            widget: 'string'